// SUNPLUS  S+core IDE generated include file.
#ifndef HYPERSCAN_RESOURCE_H__16827_23281__INCLUDED_
#define HYPERSCAN_RESOURCE_H__16827_23281__INCLUDED_

extern unsigned char* _binary_C__Users_ppcasm_Documents_score_sdk_examples_hyperscan_cd_usbloadercd_cdusbldr_bin_start;
#define RES_CDUSBLDR_BIN (unsigned char*)&_binary_C__Users_ppcasm_Documents_score_sdk_examples_hyperscan_cd_usbloadercd_cdusbldr_bin_start
extern unsigned char* _binary_C__Users_ppcasm_Documents_score_sdk_examples_hyperscan_cd_usbloadercd_cdusbldr_bin_end;
#define RES_CDUSBLDR_BIN_END (unsigned char*)&_binary_C__Users_ppcasm_Documents_score_sdk_examples_hyperscan_cd_usbloadercd_cdusbldr_bin_end


#endif //HYPERSCAN_RESOURCE_H__16827_23281__INCLUDED_
